CREATE DATABASE STUDENT;
USE STUDENT;

CREATE TABLE STUDENT_DETAILS(

	ID INT(15) NOT NULL AUTO_INCREMENT,
	LAST_NAME VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	PHONE_NO VARCHAR(10) NOT NULL,
	PRIMARY KEY(ID)
);
